### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by J0WI**
Moving to GitHub Actions due Travis policy/pricing changes.

### CODE REVIEW

**Comment by gquintard** [comment]
hi @J0WI, thanks a bunch. I assume this is a campaign on your side to flip everyone so I don't want to take too much of your time, but is there anything else we need to do here?

Do you have some documentation about the move?

**Comment by J0WI** [comment]
The CI script is provided by the docker library: https://github.com/docker-library/bashbrew/tree/master/scripts/github-actions

travis.org has recently started to [limit OSS builds](https://www.traviscistatus.com/) resulting in a huge backlog. It will be [closed down completely](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) no later than December 31st, 2020.

New pricing: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by gquintard** [comment]
noted, thanks! I just merged

While I have you, may I ask for your attention on https://github.com/docker-library/official-images/pull/8674 or is the backlog you mention preventing that at the moment?

**Comment by J0WI** [comment]
Attention for what? :confused:

**Comment by gquintard** [comment]
aren't you a maintainer there? that PR has been sitting for a few weeks and I'm unsure what we can do to push it further

**Comment by gquintard** [comment]
hum, looks like the CI failed, any idea?

**Comment by J0WI** [comment]
> aren't you a maintainer there?

nope

> hum, looks like the CI failed, any idea?

I will have a look at it in #22

**Pull request merged**
